<?php declare(strict_types=1);

namespace K118\DB\Enum;

enum VehicleCategory: string {

    case REISEZUGWAGENERSTEKLASSE = 'REISEZUGWAGENERSTEKLASSE';
    case REISEZUGWAGENZWEITEKLASSE = 'REISEZUGWAGENZWEITEKLASSE';
    case STEUERWAGENERSTEKLASSE = 'STEUERWAGENERSTEKLASSE';
    case STEUERWAGENZWEITEKLASSE = 'STEUERWAGENZWEITEKLASSE';
    case SPEISEWAGEN = 'SPEISEWAGEN';
}
